# Flow
#  1. Create an account using the signup route
#  2. Login with credentials, will return a token. Change the value 
#     of the token variable to the new token. This token lasts an hour
#  3. Open web browser to http://localhost:8080/auth/connectSpotify to get
#     a spotify token. Takes you through the OAuth 2.0 flow if haven't yet
#  4. /profile route fetches the profile
#  5. /profile/build adds data into the profile

@contentType = application/json 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRyZWVjZXBvdWxzZW5AZ21haWwuY29tIiwidXNlcklkIjoiNjM4MDMyOGY5YzM1MDhhY2VkZmFiZjMyIiwiaWF0IjoxNjY5MzQ1OTM1fQ.ns-5smNkxNcRujkc9YWb_2pc6F5bBf9jewetaqb6xC8

@spotifyToken = BQBlknMKWqPCnft7fGmUsQg4zeBWmiXYqPKrtKfHSmV10A5XKc_pwm8UlrETwhedtb7rcym1R43Bdbr8kAkIPhsb3fJ8L6fmMcFtEz0X07FYj5sswnDyB_2XChhGQHDJO2p2zYUC9okFPUdDdC40UTSAnmsVynK3XYK8WeM0ZzDvlDbgEve_Jhqjv6zzk2SCIpaLXjRZfGXBH3DsymElJz-O3O84-6i1YpLORdD4KcZK-Tk

###
# Base URL
get http://localhost:8080/

###
# Signup
post http://localhost:8080/auth/signup
Content-Type: {{contentType}}

{
  "name": "Katelyn Poulsen",
  "email": "katelynparkeshs@gmail.com",
  "password": "jukeboxPass"
}

###
# Login
post http://localhost:8080/auth/login
Content-Type: {{contentType}}

{
  "email": "dreecepoulsen@gmail.com",
  "password": "jukeboxPass"
}

###
# Logout
put http://localhost:8080/auth/logout
Authorization: Bearer {{token}}

###
get http://localhost:8080/auth/connectSpotify
Authorization: Bearer {{token}}

###
get http://localhost:8080/auth/authorizeSpotify
Authorization: Bearer {{token}}

###
get http://localhost:8080/profile/
Authorization: Bearer {{token}}

###
get http://localhost:8080/profile/build
Authorization: Bearer {{token}}

###   
get https://api.spotify.com/v1/me
Authorization: "Bearer {{spotifyToken}}"
Content-Type: {{contentType}}

###
get https://api.spotify.com/v1/tracks/1TGWNtFzNZsNeqT6oBvXtw
Authorization: "Bearer {{spotifyToken}}"

###   
get https://api.spotify.com/v1/me/tracks
Authorization: "Bearer {{spotifyToken}}"
Content-Type: {{contentType}}

###
get https://api.spotify.com/v1/me/top/tracks?limit=20&offset=40
Authorization: "Bearer {{spotifyToken}}"
Content-Type: {{contentType}}

###
GET https://api.spotify.com/v1/users/reece.poulsen/playlists
Authorization: "Bearer {{spotifyToken}}"
Content-Type: {{contentType}}

###
get http://localhost:8080/profile/users
Authorization: Bearer {{token}}

###
get http://localhost:8080/profile/songs/3Ywh8QMpMoakxcyEZ4dlql
Authorization: Bearer {{token}}

###
POST http://localhost:8080/profile/playlist/addSong
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "trackUris": [
    "spotify:track:6WqrGbkeXPT7Lqz8DNywoQ"
  ],
  "song": ""
}

###
GET http://localhost:8080/profile/637eb4b2d404743caebae6cc
Authorization: Bearer {{token}}

###
GET http://localhost:8080/profile/token/spotify
Authorization: Bearer {{token}}

###
POST http://localhost:8080/profile/followers/modify
Authorization: Basic {{token}}
Content-Type: {{contentType}}

{
  "operation": "add",
  "followerUserId": "63824a9ec3cee76fe85576fd",
  "followerUserliteId": "63824a9ec3cee76fe85576ff"
}

###
POST http://localhost:8080/profile/followers/modify
Authorization: Basic {{token}}
Content-Type: {{contentType}}

{
  "operation": "remove",
  "followerUserId": "63824a9ec3cee76fe85576fd",
  "followerUserliteId": "63824a9ec3cee76fe85576ff"
}

###
DELETE http://localhost:8080/auth/user
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "userIdToDelete": "638c0dc9b085e32b033895d6"
}